### ISSUE TITLE
Plugin doesn't identify itself to `ips`

### ISSUE THREAD

**Issue by kript** [irods/irods_capability_indexing#121]
On 4.2.7, with `irods-rule-engine-plugin-indexing          4.2.7.1`, when the `irodsServer` processes are running, they appear as `UNKNOWN` in the `ips` report.

It would be helpful if they identified the plugin that was being used, in some way.

**Comment by alanking** [comment]
What you are seeing - _I think_ - are the client connections from the delay server as it's processing the indexing tasks. This was indeed a problem in 4.2.7 and has been resolved in this issue: https://github.com/irods/irods/issues/5264

As for the request, maybe `ips` could allow for showing some "context" (?) string for a given client which could include whatever information the client chooses to display. For the delay server - which is a client to the iRODS server - could include something like the rule being executed, which would be pretty obviously intended for the indexing plugin as it would include a targeted rule engine plugin instance.

This could have potential for leaking sensitive information, though, so maybe instead of printing the whole rule we could just show the target rule engine plugin instance.

**Comment by trel** [comment]
Closing.   It should now appear as the delay server in `ips`.
